version: '3'

services:
  backend:
    build:
      context: ./../backend
      dockerfile: ./../backend/backend.dockerfile
    restart: always
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ../backend/.env
